module.exports = {
    amount: 'amount',
    creditCardNumber: 'ccnumber',
    cvv2: 'cvv',
    billingFirstName: 'firstname',
    billingLastName: 'lastname',
    billingEmailAddress: 'email',
    billingPhone: 'email',
    billingAddress1: 'address1',
    billingAddress2: 'address2',
    billingCity: 'city',
    billingState: 'state',
    billingPostalCode: 'zip',
    billingCountry: 'country',
    shippingFirstName: 'shipping_firstname',
    shippingLastName: 'shipping_lastname',
    shippingAddress: 'shipping_address1',
    shippingCity: 'shipping_city',
    shippingState: 'shipping_state',
    shippingZip: 'shipping_zip',
    shippingCountry: 'shipping_country',
    profileId:'customer_vault_id'
};
