module.exports = {
    amount: 'amount',
    creditCardNumber: 'ccnumber',
    cvv: 'cvv',
    customerFirstName: 'firstname',
    customerLastName: 'lastname',
    customerEmail: 'email',
    billingAddress: 'address1',
    billingCity: 'city',
    billingState: 'state',
    billingZip: 'zip',
    billingCountry: 'country',
    shippingFirstName: 'shipping_firstname',
    shippingLastName: 'shipping_lastname',
    shippingAddress: 'shipping_address1',
    shippingCity: 'shipping_city',
    shippingState: 'shipping_state',
    shippingZip: 'shipping_zip',
    shippingCountry: 'shipping_country',
    profileId:'customer_vault_id'
};
